apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdb-operator
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sdb-operator
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - replicationcontrollers
  - pods/exec
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  - statefulsets/status
  verbs:
  - '*'
- apiGroups:
  - memsql.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - watch
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sdb-operator
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: sdb-operator
roleRef:
  kind: Role
  name: sdb-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdb-operator-storage-access
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - "storage.k8s.io"
  resources:
  - "storageclasses"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdb-operator-storage-access
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: sdb-operator
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: sdb-operator-storage-access
  namespace: {{ .Values.namespace }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-reader
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["", "apps", "batch", "autoscaling", "memsql.com", "acid.zalan.do", "vertica.com"]
  resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - configmaps
    - secrets
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
    - cronjobs
    - jobs
    - horizontalpodautoscalers
    - memsqlclusters
    - replicationcontrollers
    - postgresqls
    - verticadbs
    - verticaautoscalers
    - verticareplicators
    - verticascrutinizers
    - pods/exec  # Added permission for pod exec
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-storage-access
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-storage-access-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: backup
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: backup-storage-access
  namespace: {{ .Values.namespace }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-reader-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: backup
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: backup-reader
  apiGroup: rbac.authorization.k8s.io
---
# Restore-specific RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restore
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restore-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["", "apps", "batch", "memsql.com"]
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restore-role-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: restore
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: restore-role
  apiGroup: rbac.authorization.k8s.io
